-- Booking sources — which OTA or agent a booking came through (ADR-0009,
-- docs/database.md §8a). Generated by drizzle-kit, then two things added by
-- hand at the end: the backfill, and the rollback note here.
--
-- Also widens reservations_source_ck with TRAVEL_AGENT. The constraint is
-- dropped and re-added; on a large reservations table that takes a full scan
-- under an ACCESS EXCLUSIVE lock, so run it when the desk is quiet.
--
-- ROLLBACK (Definition of Done): reversible.
--   ALTER TABLE reservations DROP CONSTRAINT reservations_source_ck;
--   ALTER TABLE reservations ADD CONSTRAINT reservations_source_ck
--     CHECK (source IN ('DIRECT','OTA','WALK_IN','PHONE','EMAIL'));
--     -- fails if any TRAVEL_AGENT row exists: reclassify those first.
--   ALTER TABLE reservations DROP COLUMN booking_source_id;
--   DROP TABLE booking_sources;
-- Rolling back loses which OTA each hand-keyed booking named; the category
-- in `source` survives.

CREATE TABLE "booking_sources" (
	"id" uuid PRIMARY KEY NOT NULL,
	"organization_id" uuid NOT NULL,
	"property_id" uuid NOT NULL,
	"name" text NOT NULL,
	"kind" text NOT NULL,
	"channel_type" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "booking_sources_kind_ck" CHECK ("booking_sources"."kind" IN ('OTA','TRAVEL_AGENT')),
	CONSTRAINT "booking_sources_channel_type_ck" CHECK ("booking_sources"."channel_type" IS NULL OR "booking_sources"."channel_type" IN ('MOCK_OTA','AGODA','BOOKING_COM','EXPEDIA','TRIP_COM','AIRBNB','DIRECT'))
);
--> statement-breakpoint
ALTER TABLE "reservations" DROP CONSTRAINT "reservations_source_ck";--> statement-breakpoint
ALTER TABLE "reservations" ADD COLUMN "booking_source_id" uuid;--> statement-breakpoint
ALTER TABLE "booking_sources" ADD CONSTRAINT "booking_sources_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "booking_sources" ADD CONSTRAINT "booking_sources_property_id_properties_id_fk" FOREIGN KEY ("property_id") REFERENCES "public"."properties"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "booking_sources_property_name_uq" ON "booking_sources" USING btree ("property_id",lower("name"));--> statement-breakpoint
CREATE UNIQUE INDEX "booking_sources_property_channel_type_uq" ON "booking_sources" USING btree ("property_id","channel_type") WHERE "booking_sources"."channel_type" IS NOT NULL;--> statement-breakpoint
CREATE INDEX "booking_sources_property_idx" ON "booking_sources" USING btree ("property_id","is_active");--> statement-breakpoint
ALTER TABLE "reservations" ADD CONSTRAINT "reservations_booking_source_id_booking_sources_id_fk" FOREIGN KEY ("booking_source_id") REFERENCES "public"."booking_sources"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reservations" ADD CONSTRAINT "reservations_source_ck" CHECK ("reservations"."source" IN ('DIRECT','OTA','WALK_IN','PHONE','EMAIL','TRAVEL_AGENT'));
--> statement-breakpoint
-- Every property that exists today starts with the usual OTAs, the same list
-- the seed and the "add defaults" endpoint use. New properties get them from
-- the dashboard; a migration cannot know about properties created later.
INSERT INTO "booking_sources" ("id", "organization_id", "property_id", "name", "kind", "channel_type")
SELECT gen_random_uuid(), p."organization_id", p."id", d."name", 'OTA', d."channel_type"
FROM "properties" p
CROSS JOIN (VALUES
  ('Agoda', 'AGODA'),
  ('Booking.com', 'BOOKING_COM'),
  ('Expedia', 'EXPEDIA'),
  ('Trip.com', 'TRIP_COM'),
  ('Airbnb', 'AIRBNB'),
  ('Traveloka', NULL)
) AS d("name", "channel_type");
